# fly.toml app configuration file generated for saber-bldgaudittool on 2026-04-27T18:59:47-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'saber-bldgaudittool'
primary_region = 'dfw'

[build]
  dockerfile = 'Dockerfile'

[env]
  UPLOADS_DIR = '/data/uploads'

[[mounts]]
  source = 'user_uploads'
  destination = '/data/uploads'
  initial_size = '1gb'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

  [http_service.concurrency]
    type = 'requests'
    hard_limit = 10
    soft_limit = 5

[[vm]]
  memory = '1gb'
  cpus = 1
